# Generated by Django 2.0.4 on 2018-11-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
